### ISSUE TITLE
Compiling Osmap-viewer

### ISSUE THREAD

**Issue by makolele12** [AlejandroSilvestri/Osmap-viewer#2]
Hi,

My setup:

--> Ubuntu 20.04
--> OpenCV 3.2.0 installed from source with contrib modules
--> ORB-SLAM2 with Osmap integrated and working

I am a bit confused on how to install Osmap-viewer.
As far as I understood, it is needed to copy the files:

--> include/Osmap.h
--> src/Osmap.cpp

and overwrite the previous ones copied when installing osmap.

Howerver, when doing so, I try to compile with and 

``In file included from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:60:21: error: expected ‘)’ before ‘*’ token
   60 |  OsmapMapPoint(Osmap*);
      |               ~     ^
      |                     )
/home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:70:21: error: expected ‘)’ before ‘*’ token
   70 |  OsmapKeyFrame(Osmap*);
      |               ~     ^
      |                     )
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:25:14: error: conflicting declaration ‘unsigned int ORB_SLAM2::MapPoint::nNextId’
   25 | unsigned int MapPoint::nNextId = 0;
      |              ^~~~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrame.h:24,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:42,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/MapPoint.h:86:30: note: previous declaration as ‘long unsigned int ORB_SLAM2::MapPoint::nNextId’
   86 |     static long unsigned int nNextId;
      |                              ^~~~~~~
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:26:14: error: conflicting declaration ‘unsigned int ORB_SLAM2::KeyFrame::nNextId’
   26 | unsigned int KeyFrame::nNextId = 0;
      |              ^~~~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:42,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrame.h:123:30: note: previous declaration as ‘long unsigned int ORB_SLAM2::KeyFrame::nNextId’
  123 |     static long unsigned int nNextId;
      |                              ^~~~~~~
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp: In function ‘int main(int, char**)’:
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:34:11: error: no matching function for call to ‘ORB_SLAM2::System::System()’
   34 |    System system;
      |           ^~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:45,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/System.h:63:5: note: candidate: ‘ORB_SLAM2::System::System(const string&, const string&, ORB_SLAM2::System::eSensor, bool)’
   63 |     System(const string &strVocFile, const string &strSettingsFile, const eSensor sensor, const bool bUseViewer = true);
      |     ^~~~~~
/home/arevo/Dev/ORB_SLAM2_osmap/include/System.h:63:5: note:   candidate expects 4 arguments, 0 provided
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:36:36: error: no matching function for call to ‘ORB_SLAM2::KeyFrameDatabase::KeyFrameDatabase()’
   36 |    system.mpKeyFrameDatabase = new KeyFrameDatabase;
      |                                    ^~~~~~~~~~~~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrame.h:30,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:42,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrameDatabase.h:46:5: note: candidate: ‘ORB_SLAM2::KeyFrameDatabase::KeyFrameDatabase(const ORBVocabulary&)’
   46 |     KeyFrameDatabase(const ORBVocabulary &voc);
      |     ^~~~~~~~~~~~~~~~
/home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrameDatabase.h:46:5: note:   candidate expects 1 argument, 0 provided
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:59:33: error: ‘std::set<ORB_SLAM2::MapPoint*> ORB_SLAM2::Map::mspMapPoints’ is protected within this context
   59 |    for(auto pMP : system.mpMap->mspMapPoints)
      |                                 ^~~~~~~~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/MapPoint.h:26,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrame.h:24,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:42,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/Map.h:70:25: note: declared protected here
   70 |     std::set<MapPoint*> mspMapPoints;
      |                         ^~~~~~~~~~~~
/home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:60:41: error: ‘cv::Mat ORB_SLAM2::MapPoint::mWorldPos’ is protected within this context
   60 |     mapPointsCloud.push_back(Vec3f(pMP->mWorldPos));
      |                                         ^~~~~~~~~
In file included from /home/arevo/Dev/ORB_SLAM2_osmap/include/KeyFrame.h:24,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/include/Osmap.h:42,
                 from /home/arevo/Dev/ORB_SLAM2_osmap/Examples/Monocular/osmap-viewer.cpp:15:
/home/arevo/Dev/ORB_SLAM2_osmap/include/MapPoint.h:118:14: note: declared protected here
  118 |      cv::Mat mWorldPos;
      |              ^~~~~~~~~
make[2]: *** [CMakeFiles/osmap-viewer.dir/build.make:63: CMakeFiles/osmap-viewer.dir/Examples/Monocular/osmap-viewer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: CMakeFiles/osmap-viewer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
``

**Comment by makolele12** [comment]
I just understood this must be compiled separately from ORB_SLAM2, I did it with CMake and finally got it working.
